### ISSUE TITLE
"Unable to find resource"

### ISSUE THREAD

**Issue by axel-rutz** [sanpii/effitask#24]
## What are the minimum necessary steps to reproduce this issue?

* Build the app on current ubuntu like described in readme.

## What happens?

On startup i see messages

`Unable to find stylesheet`

`Unable to find resource inbox.png`

(and 6 other pngs)

I see the bin in effitask/target/release, and i see the resource files in effitask/resources.

**Comment by sanpii** [comment]
Sorry, the documentation was ambiguous. After the installation, you should execute `/usr/bin/effitask`.

If you want to test it from source, you could simply execute `cargo run`.

I updated the README, fell free to reopen the issue if it’s still unclear.

**Comment by axel-rutz** [comment]
Uuups, i maybe forgot a maybe important circumstance: I compiled it in my userland dir and want to execute it there. Maybe this boils down to an issue like "How do i install without sudo".

(Looks like i can not reopen)

**Comment by sanpii** [comment]
I updated the Makefile, now you can do:

```
 make install PREFIX=$HOME/.local/
```

The files will be installed in `~/.local/bin` (add it to your `PATH`) and `~/.local/share`, the default value for `XDG_DATA_HOME` variable where the program looks for assets.

**Comment by axel-rutz** [comment]
Yeah thanks this works and now i see shiny buttons!
