### ISSUE TITLE
Task deleted when adding note

### ISSUE THREAD

**Issue by geek-merlin** [sanpii/effitask#25]
## What are the minimum necessary steps to reproduce this issue?

* on ubuntu linux 1804
* (if it matters: install in userland as introduced in #24)
* add a task "foo"
* doubleclick to edit, add note "bar", clock "OK"

## What happens?

todo.txt loses some tasks
(not all, it looks like the edited and all following)

## What were you expecting to happen?

;-)

## Please paste any error or log messages here

"Task updated"
"Unable to save tasks: FIle or directory nor found (OS error 2)

## Any other details

…

**Comment by cypa** [comment]
My todo.txt file was truncated, only 3 lines left.
I've had a file like this
```
(I) русский текст в строке
(L) ещё одна строка
(I) ещё больше строка даже с английскими буквами немножко foo:foo
- и много строк с минусами в начале
- ещё ....
- и ещё ...
- 20 more lines with minuses
```

and all the lines starting with '-' were truncated on first save event in effitask
(btw I have a backup copy of the file so I lost nothing)

**Comment by sanpii** [comment]
Sorry, I forgot this issue…

This bug occurs when the notes directory doesn’t exist. Now I create the directory if doesn’t exist and I continue to save task if this fail.
