### ISSUE TITLE
Time out messages

### ISSUE THREAD

**Issue by geek-merlin** [sanpii/effitask#29]
## What are the minimum necessary steps to reproduce this issue?

Do something and see a message

## What happens?

Message sticks.
Clultters up the screen.
On my system, after some messages the effective height has diminished so much that i have to scroll to see task-edit's OK button.

## What were you expecting to happen?

Message disappears after some seconds.

**Comment by sanpii** [comment]
Do you have a screenshot? I suspect debug message, do you build binary in release mode?

**Comment by axel-rutz** [comment]
![effitask](https://user-images.githubusercontent.com/15613398/50509905-ddd38380-0a87-11e9-919b-ed81b0942816.png)

It looks like it says "Task updated". 

> ... release mode.

So if this is just debug messages that can be switched off with complie options (did not get this yet so more foolproof documentation might help ;-), then we can surely close this.

**Comment by sanpii** [comment]
Ok, I missundestood your request.

I already tried but it’s not easy to do.

**Comment by sanpii** [comment]
I completly redesigned how the application displays notifications:
![2020-04-08-133426_1676x951_scrot](https://user-images.githubusercontent.com/113045/78780057-53721300-799e-11ea-9305-ae42fcadacb8.png)
