### ISSUE TITLE
Could not compile `relm-attributes`

### ISSUE THREAD

**Issue by jcz1** [sanpii/effitask#5]
Debian unstable, rustc 1.23.0+dfsg1-1

cargo build  --release
   Compiling relm-attributes v0.11.0
error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/jackc/.cargo/registry/src/github.com-1ecc6299db9ec823/relm-attributes-0.11.0/src/lib.rs:22:1
   |
22 | #![feature(proc_macro)]
   | ^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
error: Could not compile `relm-attributes`.

**Comment by sanpii** [comment]
You should use the nighhly version of rusr. If you use [rustup](https://www.rustup.rs/) the [rust-toolchain](https://github.com/sanpii/effitask/blob/master/rust-toolchain) set the good toolchain for you.

**Comment by sanpii** [comment]
I added a note about the rust version (c73cb97846b5aafaa127cac669cdf8800cb65ada). Feel free to reopen this issue if that doesn’t solve your problem.

**Comment by jcz1** [comment]
I have rustc 1.23.0 (2018-01-04) from distribution and because i don't like this "curl something | sudo sh" things, i have to wait for some more stable versions.

Anyway, thx for this note and Effitask, it seems very promising :)

**Comment by sanpii** [comment]
@jcz1 there is a unofficial PPA with rust nightly https://launchpad.net/~infinity0/+archive/ubuntu/rust-nightly

**Comment by jcz1** [comment]
i saw that... 1.15.0~~nightly.20161206+dfsg1-1 ouch :-)
