### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by darrenldl** [sanpii/effitask#6]
I am somewhat interested in creating a TUI tool in Rust for using todotxt files, and may use this project as a basis, and thus would like to know if your work is licensed under any particular license.

Many thanks!

**Comment by darrenldl** [comment]
Whoops, missed the LICENSE file, closing issue.

Silly me, sorry!

**Comment by sanpii** [comment]
> I am somewhat interested in creating a TUI tool in Rust for using todotxt files

Great 😃 

Let me know if you copy/paste many lines of code, it’s probably a good idea to create a new crate.
