### ISSUE TITLE
Tasks shouldn't be required to be HTML escaped

### ISSUE THREAD

**Issue by quasipedia** [sanpii/effitask#9]
The app throws errors in loading files having tasks with the character `&` in it.

`(.:5742): Gtk-WARNING **: Failed to set text 'P&T keep focus on long term <b>+HoWE</b>' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;`

As far as I know, the specs for todo.txt are plain text.

**Comment by sanpii** [comment]
Your task is plain text, but the [pango markup](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html) is enable to improve task display (context/project emphasis and cliquable URL).

I need to improve [Task::markup_subject](https://github.com/sanpii/effitask/blob/master/src/tasks/task.rs#L23) to escape `&`.

**Comment by sanpii** [comment]
https://github.com/gtk-rs/glib/issues/280
